apiVersion: v1
kind: Service
metadata:
  name: yasirifthikar-prj2-service
spec:
  type: NodePort
  selector:
    app: yasirifthikar-prj2-app
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3030
    nodePort: 32000
